name: Chess API Backend CI

on:
  push:
    branches: [ "main" ] # При прямом пуше в main
  pull_request:
    branches: [ "main" ] # При открытии PR в ветку main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./...

      - name: Verify Build
        run: go build -o /dev/null ./cmd/server/main.go